# kubectl apply --namespace=jupyterhub -f azure_file_pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-aksshare-fft
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: stjupyterhub-secret
    secretNamespace: jupyterhub
    shareName: aksshare-fft
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aksshare-fft
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: pvc-aksshare-fft
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi