# https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-file
# https://docs.microsoft.com/en-us/azure/aks/concepts-storage#storage-classes
# https://github.com/Azure/AKS/issues/929
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: landerhub-azurefile
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
  location: uksouth
  storageAccount: stlthlandercore
  secretNamespace: default
  secretName: stlthlandercore-secret
  resourceGroup: rg-lander-core-prd
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
  - metadata
allowVolumeExpansion: true
reclaimPolicy: Retain
